### PR TITLE
Add PHP8 support

### LINKED ISSUE #8: Support for PHP 8
It would be great to support PHP 8

### PR DESCRIPTION
**Pull request by norkunas**
Closes #8

### CODE REVIEW

**Comment by stof** [comment]
Looks like Travis is not running. The CI setup does not seem to be working anymore...

**Comment by norkunas** [comment]
@salaros do you plan to maintain this library or is it abandoned?

**Comment by salaros** [comment]
@norkunas that's for PR! I just haven't noticed it (I receive tons of notifications on GitHub)

@stof I fixed all the builds, PHP 5.4/5.5 versions work only on Ubuntu 14.04.
PHP 7.3+ uses PHPUnit which changed syntax of expected exceptions, but it uses :class constrain which is unsupported by PHP 5.4 (parse error), so it was a mess to make it work.
Unfortunately PHP is not my primary language anymore, even though this lib is alive, it has slightly lower priority

**Comment by salaros** [comment]
Everything is fine now Travis https://travis-ci.org/github/salaros/is-biz-mail-php/builds/760443292

**Comment by thedotedge** [comment]
hi @salaros! Will you tag a new version with php8 support, please?

**Comment by salaros** [comment]
hey @thedotedge I did it. Sorry for the delay

**Pull request merged**
